### ISSUE TITLE
Match equals() isn't correctly implemented

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#11]
These things are wrong in my opinion:

1. Variable is named just 'o'
2. The equals method doesnt follow the proper conformation
    (1. NULL-Check, 2. CLASS-Check, 3. EQUALS-Check)
    -> Comparing 'o' with == seems confusing to me
3. The compare part is kinda long, maybe use the hash instead?

**Comment by czarnecki** [comment]
The equals method is fine.
