### ISSUE TITLE
Design datepicker

### ISSUE THREAD

**Issue by ccaylak** [adessoAG/adessoKicker#114]
Currently it depends on your browser choice. Some browsers have awful datepickers.

That's why I would suggest using [Tempus Dominus Bootstrap 4](https://tempusdominus.github.io/bootstrap-4/Usage/), I don't mind if you want to use something else. You can even disable days of a week, for instance saturday/sunday.

**Comment by JanSchneider1** [comment]
Seems like a good idea

**Comment by JanSchneider1** [comment]
Implemented in branch 'frontend'

**Comment by JanSchneider1** [comment]
Not ideal to work with ThymeLeaf, wont fix for now
