### ISSUE TITLE
Can't accept/decline notifications when I'm using a small gadget

### ISSUE THREAD

**Issue by ccaylak** [adessoAG/adessoKicker#146]
![Hi](https://puu.sh/CVVVy/492748ab43.png)

**Comment by JanSchneider1** [comment]
Something I noticed too, maybe its fixed, as the text is now 'block' style, more checks needed.

**Comment by JanSchneider1** [comment]
It doesn't happen anymore, but the text gets cut off sometimes, but I'm not quite shure if it appears in a 'real' environment. So I will label this won't fix for now

**Comment by Flo4l** [comment]
Works fine for me
