### ISSUE TITLE
The purpose of the search bar at '/ranking'

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#167]
Many said that the search bar at the ranking site is unneccessary or confusing, so should we remove it?
I would also suggest that you can click on the names in the ranking list leeding to the profile of the user.

**Comment by JanSchneider1** [comment]
Another option would be to let the searchbar work like the one on the profile page, loading a users profile

**Comment by czarnecki** [comment]
The people I've showed this to found the searchbar on the _profile_ confusing and said that the one on the ranking page would be enough.

**Comment by Flo4l** [comment]
I think the searchbar in the ranking page should lead to the rankig site which is containing the searched user. Maybe the searched user could then be highlighted.
An approach to this would be to simpy redirect to the site number: (RankOfPlayer -1) / SizeOfList

**Comment by JanSchneider1** [comment]
Oh i did'nt get that, so which one should we remove

**Comment by czarnecki** [comment]
> 
> 
> Oh i did'nt get that, so which one should we remove

According to the ones I've asked you should remove the searchbar on `profile.html`

**Comment by Flo4l** [comment]
Agreed, the page of the other players should be reachable by the ranking list

**Comment by JanSchneider1** [comment]
That seem like a good idea, so the searchbar on the ranking side links to the user profiles right?

**Comment by JanSchneider1** [comment]
Then the searchbar wound't load the users ranking page?

**Comment by Flo4l** [comment]
> 
> 
> I think the searchbar in the ranking page should lead to the rankig site which is containing the searched user. Maybe the searched user could then be highlighted.
> An approach to this would be to simpy redirect to the site number: `(int)(RankOfPlayer -1) / SizeOfList`

**Comment by JanSchneider1** [comment]
Then clicking on a user in the ranking table would go to the profile page?

**Comment by Flo4l** [comment]
Yes, see #175

**Comment by czarnecki** [comment]
> `(int)(RankOfPlayer -1) / SizeOfList`

Casting isn't needed here as diving by ints in java produces an int.

**Comment by JanSchneider1** [comment]
Then I will do it like you suggested
