### ISSUE TITLE
Allow users who aren't logged in to view pages

### ISSUE THREAD

**Issue by czarnecki** [adessoAG/adessoKicker#18]
The way it is right now only logged in users can access the site. Some pages, like the to be done ranking page, should be able to be viewed by anyone.

**Comment by JanSchneider1** [comment]
Considering the principle of the 'Minimal viable product' it would be necessary as it would cause a lot of work and care making every site viewable without loggin in.
Like the 'adesso profiler' our application is only company intern, so there is no real need making it visble for others.

**Comment by czarnecki** [comment]
The thing is that, according to the specifications Tom laid out, some view, like the ranking, should be visible to everybody.

**Comment by JanSchneider1** [comment]
But still everyone at adesso, can theoretically login easily. Who else should see that (I mean only 'adessi' have access to the table)

**Comment by czarnecki** [comment]
Our specifications are to allow user who aren't logged in to be able to see some pages like the ranking and forcing everybody to log in for this would add another barrier of entry.

**Comment by ccaylak** [comment]
I remember when I've asked Tom this particular question, if users should be able to visit pages without being logged in. The only page that would be public to everyone is the ranking page, everything else would make nonsense and cause problems.
