### ISSUE TITLE
1.0 Release tasks

### ISSUE THREAD

**Issue by ccaylak** [adessoAG/adessoKicker#187]
Tom told us to make a small list.
What else is need except the following?

- [ ] Webserver
- [ ] Mailserver
- [ ] Advertising (QR-Code + neat text)
- [ ] Meeting with Tom

**Comment by ccaylak** [comment]
What else should be in our check list?

**Comment by JanSchneider1** [comment]
Maybe add player statistics like the charts js graphs.
I also would like to optimize the responsibility for user on smaller devices mainly smart phones
