### ISSUE TITLE
Add user statistics on the profile page using ChartJS

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#194]
We should create a graph tracking the user ranking position over time (x:= Time, y:= RankingPos).
What other graph should we create that could be interesting/useful?

**Comment by Flo4l** [comment]
The other could be a graph displaying `wins - losses` over time.
so you would get a step up if you win, and a stp down if you loose.

**Comment by czarnecki** [comment]
We currently can't track anything over time so this wouldn't be possible.
We could display how many wins and or losses a player had on a day but that's it.

**Comment by Flo4l** [comment]
Then we just count the wins - losses of a matchday of a player.
Every step in the timeline would be a day in which the user played at least one match.

**Comment by JanSchneider1** [comment]
So we have a statistic tracking the rank of an user over time this is fine to me.

But I have a problem with the graph for (wins minus losses). I think it would be good if 
we add a graph displaying the win ratio over time and change the (wins minus losses) graph as its hard to understand in my opinion.
I would recommend changing it that way so it displays the wins and the losses in a seprate curve (maybe red and blue) and you can see the (wins minus losses) in the gap/interval between the two curves.

**Comment by Flo4l** [comment]
In my opinion the `wins - losses` graph is cool and i like it.
I also think it is not complicate to understand. We just need to finde a asy to understand headline for it
that expresses the meaning of 'matches in positive' or something like that in a better way.

As long as this value is above 0 you can live with good conscience :D

**Comment by Flo4l** [comment]
I would like to handle this topic like:
Everyone makes some further suggestions for more charts.
We'll implement those charts and then we'll take a look together with tom which of them are the best.
