### ISSUE TITLE
Implement the 'adesso-font' (Klavika) in our pages

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#197]

**Comment by ccaylak** [comment]
There's a way to implement _(@font-face)_ custom fonts, that are not installed by default from your own server.
In the following picture you'll see why I'm mailing Tom for **permission** and maybe the path where this font is located at.

![Proof](https://puu.sh/CYM8h/6d05f6806a.png)

**Comment by ccaylak** [comment]
Tom mailed CCO if we get permission to use Klavika, I'll have to ask project board team how they added this font to their project.
