### ISSUE TITLE
Redirection of clicking on the own rankig

### ISSUE THREAD

**Issue by Flo4l** [adessoAG/adessoKicker#203]
When you're browsing the first page (ranks 1-10) and you're clicking on your own profile(rank 145)
should your profile be opened - like every other one in the list, or should the ranking page, that contains your stats (rank 141-150) be opened?

You could then again click on your profile, which now would act like all others and redirect to your profile.

**Comment by ccaylak** [comment]
It should redirect to your profile, would be kinda confusing, everything else redirects to the specific profile too
