### ISSUE TITLE
Alignment of player names in ranking

### ISSUE THREAD

**Issue by Flo4l** [adessoAG/adessoKicker#214]
The name of the players should be aligned to the left like the other stats.

**Comment by JanSchneider1** [comment]
All stats are aligned in the center. The player names are aligned to the right as its the way the 'adesso profiler' does and its better to read in my opinion. I would like to hear what the others think

**Comment by czarnecki** [comment]
Doesn't really matter to me how it's aligned as long as it looks alright.

**Comment by Flo4l** [comment]
I think the alignmnt is not what disturbs me, it is more that the spacing between name and wins is much smaller that the spacing of the other stats.
This really makes my eyes bleed

**Comment by ccaylak** [comment]
I don't really care just make it uniform. That it looks intended.

**Comment by JanSchneider1** [comment]
![Unbenannt](https://user-images.githubusercontent.com/43335130/54354284-88eee480-4656-11e9-86b7-5395e8c6b7aa.PNG)

**Comment by JanSchneider1** [comment]
I changed it back to centered text

**Comment by czarnecki** [comment]
Resolved in 6fbb55e0fd90e90af559d30329556f3e7186bc3d
