### ISSUE TITLE
Should the search bar closes after you selected an item?

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#217]
What schould happen in the search bars after you selected an user on 'matchresult.html'?

1) Allow the user to select an other user instead, so the menu doens't closes instantly (the way it currently is)

2) The user menu should close after you selected something, so the user can get to the next input quicker and has to click on the search bar again to select another user

**Comment by ccaylak** [comment]
2, because that's what the user would expect to happen, 1 would confuse

**Comment by JanSchneider1** [comment]
I did the 2nd way as I agree with @ccaylak. It' a single line of code, so we can always change it
