### ISSUE TITLE
Ranking table name misaligned

### ISSUE THREAD

**Issue by czarnecki** [adessoAG/adessoKicker#224]
On master "name" in the table header on ranking.html is misaligned.
![misaligned_name](https://i.imgur.com/dBzRt9J.png)
This is with an empty list.

**Comment by czarnecki** [comment]
This seem to occur due to vertical-align: top !important;` in `.thead-name` in `ranking.less`.
@JanSchneider1 can one remove the attribute safely  or will it break something?

**Comment by JanSchneider1** [comment]
Im currently changing this please see Issue #214

**Comment by czarnecki** [comment]
The issue persists even after 6fbb55e0fd90e90af559d30329556f3e7186bc3d.
Name is a bit higher than the other labels.

**Comment by JanSchneider1** [comment]
It's really hard to solve this correctly. In my version it isn't as dominant as in your picture.
The problems are that the positioning and scale of the text is based on the font metrics + we use Fontawesome, which is also a font, causing a lot of trouble. I'm mean its solvable, but I can't really get into it. If you want you can check out this article about this topic: http://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align#fnref-1

**Comment by ccaylak** [comment]
In my version it looks aligned properly.
