### ISSUE TITLE
How we should format CSS/LESS

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#240]
For CSS it's important that the code is readable. But the trouble with CSS using normal coding conventions lead to huge amount of lines of code making the code appeal more complex and less 'beautiful' as it requires a lot of scrolling. So there are no real preferences how CSS Code should be formatted, reaching from writing a hole class in a **single-line** are making rediculous amounts of tabs and spaces, it all up to personal preferences.

In the following I will show you, how I like to structure my code. And if you agree with me, if possible, I would like to change the auto formatting that way.

Firstly I like to write a class containing a **single attribute as a single-line**
```
#myID {color: black}
```
Secondly I like to write classes with multiple attributes as multi-line, but with out a space after the
First '{' and without an empty line, as it make the code look more structured and shorter
```
.myClass{
    color: black;
    font-size: 20px;
    width: 50%;
}
```

And for the last rule I like to order classes that have a connection in block or use the features of LESS

(So note that I grouped every thing belonging to 'date' is structured in a block)

```
.#date { . . . }
.datepicker { . . . }
.datepicker:hover { . . . }
.datepicker-label{ . . . }
.datepicker-label:hover{ . . . }

.football { . . . }
```

You should also use the less Feature **'&' with compiles to the selector of the block**
```

#date { . . . }
.datepicker {
   . . .
   &:hover { . . . }
   &-label { 
       . . . 
       &:hover{ . . . }
    }
}

.football { . . . }
```

Let me know what you thing of my way of structuring CSS ;)

**Comment by JanSchneider1** [comment]
(Git Issues doesn't allow tabs)

**Comment by Flo4l** [comment]
looks good to me.
One thing: pls do the spacing also on multi line css classes.

**Comment by Flo4l** [comment]
How does your related block style look with multi line classes?

**Comment by JanSchneider1** [comment]
> 
> 
> looks good to me.
> One thing: pls do the spacing also on multi line css classes.

Yeah you're right
