### ISSUE TITLE
Minor text changes

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#257]
![Unbenanntsdadasd](https://user-images.githubusercontent.com/43335130/54670506-12d5fc00-4af4-11e9-8134-5f8ca6f83e10.PNG)

Change 'Kicker-Spiel anfragen' to 'Kicker-Spiel eintragen' as thats was Tom requested us to do

**Comment by ccaylak** [comment]
I've already changed this in my Branch to Ergebnis eintragen/Record Results
