### ISSUE TITLE
Implement events in email, match, notification

### ISSUE THREAD

**Issue by czarnecki** [adessoAG/adessoKicker#41]
As soon as the event API is available we need to implement it in email, match and notification.
- [x] email
- [x] match
- [x] notification

Relates to #37

**Comment by ccaylak** [comment]
As I'm currently working on Events for Mails I'n questioning myself if Emails really need Events. As this Service basically just sends emails and doesn't do DML in our database.

**Comment by Flo4l** [comment]
Yes they should use events to determine when a mail for validation have to be sent and to tell the other services that a user vaidated a match. You don't need to create new events. just set up a listener for MatchCreatedEvents and publish MatchVerifiedEvent if a user accept a match via mail.

**Comment by ccaylak** [comment]
My Idea was basically to send a simple Email like:
>Your recently played Match against (Here is the other Team aka Team B) needs to be verified. (Winner Team) won. Click here to verify (which is just a link to (/notifications/accept/id) or here to decline(/notifications/decline/id)

Here an example with "real" data
>Your recently played Match against [Florian Albers](localhost/u/1) and [Jan Schneider](localhost/u/2) needs to be verified. Your team won. Click [here](localhost/notifications/accept/id) to verify or [here](localhost/notifications/decline/id) to decline.

Maybe things get clearer now.

**Comment by ccaylak** [comment]
Nevermind, I understand what you mean.
