### ISSUE TITLE
Create mock-ups to mimic profiler design

### ISSUE THREAD

**Issue by czarnecki** [adessoAG/adessoKicker#5]
The front end is supposed to look similar to the profiler and we need mock-ups to agree on a design.

**Comment by JanSchneider1** [comment]
![header](https://user-images.githubusercontent.com/43335130/53010400-1ff0c400-343e-11e9-8ad4-202b0e86e38e.png)
![rankinglist](https://user-images.githubusercontent.com/43335130/53010405-23844b00-343e-11e9-9cf8-195490889c6b.png)
![matchresult](https://user-images.githubusercontent.com/43335130/53010408-25e6a500-343e-11e9-831d-fcd17b5ae5a3.png)
![matchresult copy](https://user-images.githubusercontent.com/43335130/53010409-267f3b80-343e-11e9-9afd-7dd17b416a35.png)

These are the mockups for all the sites we want to have, please consider giving feedback.

**Comment by czarnecki** [comment]
> ![header](https://user-images.githubusercontent.com/43335130/53010400-1ff0c400-343e-11e9-8ad4-202b0e86e38e.png)

The dropdown feels kinda useless as it is almost identical to the header in terms of what you can do in it.

**Comment by JanSchneider1** [comment]
> 
> 
> > ![header](https://user-images.githubusercontent.com/43335130/53010400-1ff0c400-343e-11e9-8ad4-202b0e86e38e.png)
> 
> The dropdown feels kinda useless as it is almost identical to the header in terms of what you can do in it.

That is intentional, like the 'adesso profiler' the header contains all links and when you view it with smaller screens like a mobile device, bootstrap hides the links and you can easily use the links from the dropdown. Like that it would secure responsiveness and usability as the user can always access every part of the site via the dropdown

**Comment by ccaylak** [comment]
I like the design in general. I have only some points to complain about which are not really necessary.
I would prefer to rename _Rankinglist_ to _Ranking_ and Spieler 1 of Team 1 is always the User himself.

**Comment by JanSchneider1** [comment]
> 
> 
> I like the design in general. I have only some points to complain about which are not really necessary.
> I would prefer to rename _Rankinglist_ to _Ranking_ and Spieler 1 of Team 1 is always the User himself.

Good ideas, approved!

**Comment by Flo4l** [comment]
I like the design!
The only thing I would change is the text in the request.
Good work!

**Comment by JanSchneider1** [comment]
> 
> 
> I like the design!
> The only thing I would change is the text in the request.
> Good work!

Was more like a place holder, we can always change that in the end

**Comment by czarnecki** [comment]
You know that it's possible to have the dropdown only appear when the screen gets small enough?



On Tue, Feb 19, 2019 at 12:14 PM +0100, "JanSchneider1" 
<notifications@github.com> wrote:







The dropdown feels kinda useless as it is almost identical to the header in terms of what you can do in it.

That is intentional, like the 'adesso profiler' the header contains all links and when you view it with smaller screens like a mobile device, bootstrap hides the links and you can easily use the links from the dropdown. Like that it would secure responsiveness
 and usability as the user can always access every part of the site via the dropdown
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adessoAG/adessoKicker","title":"adessoAG/adessoKicker","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/adessoAG/adessoKicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JanSchneider1 in #5: \u003e \r\n\u003e \r\n\u003e \u003e ![header](https://user-images.githubusercontent.com/43335130/53010400-1ff0c400-343e-11e9-8ad4-202b0e86e38e.png)\r\n\u003e \r\n\u003e The dropdown feels kinda useless as it is almost identical to the header in terms of what you can do in it.\r\n\r\nThat is intentional, like the 'adesso profiler' the header contains all links and when you view it with smaller screens like a mobile device, bootstrap hides the links and you can easily use the links from the dropdown. Like that it would secure responsiveness and usability as the user can always access every part of the site via the dropdown"}],"action":{"name":"View Issue","url":"https://github.com/adessoAG/adessoKicker/issues/5#issuecomment-465089506"}}}[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/adessoAG/adessoKicker/issues/5#issuecomment-465089506",
"url": "https://github.com/adessoAG/adessoKicker/issues/5#issuecomment-465089506",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]




 












Achtung Adressänderung:
Bitte richten Sie Ihre Post an die Unternehmenszentrale zukünftig an: adesso AG
| Adessoplatz 1 | 44269 Dortmund


-------------------------------------------------------     >>> business. people. technology. <<<-------------------------------------------------------adesso AG mit Sitz in DortmundVorstand: Michael Kenfenheuer (Vors.), Christoph Junge, Dirk Pothen, Andreas PrenneisVorsitzender des Aufsichtsrates: Prof. Dr. Volker GruhnAmtsgericht Dortmund HRB 20663

**Comment by JanSchneider1** [comment]
@czarnecki What problem are you trying to solve exactly?
The dropdown seems fine to me as it also contains the logout button and for
the user no matter what device he uses he can always access the pages in the dropdown.
And if he uses a computer or laptop he can also use the link in the header.

**Comment by czarnecki** [comment]
Just wanted mention that the dropdown can only appear on specific sizes as it sounded like that you mostly wanted it for mobile users.


Anyway I sent this from my mobile and didn't see that the issue was closed and didn't know this Mail would reopen the issue.




On Thu, Feb 21, 2019 at 7:43 AM +0100, "JanSchneider1" 
<notifications@github.com> wrote:



@czarnecki What problem are you trying
 to solve exactly?
The dropdown seems fine to me as it also contains the logout button and for
the user no matter what device he uses he can always access the pages in the dropdown.
And if he uses a computer or laptop he can also use the link in the header.
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adessoAG/adessoKicker","title":"adessoAG/adessoKicker","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/adessoAG/adessoKicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JanSchneider1 in #5: @czarnecki What problem are you trying to solve exactly?\r\nThe dropdown seems fine to me as it also contains the logout button and for\r\nthe user no matter what device he uses he can always access the pages in the dropdown.\r\nAnd if he uses a computer or laptop he can also use the link in the header."}],"action":{"name":"View Issue","url":"https://github.com/adessoAG/adessoKicker/issues/5#issuecomment-465881381"}}}[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/adessoAG/adessoKicker/issues/5#issuecomment-465881381",
"url": "https://github.com/adessoAG/adessoKicker/issues/5#issuecomment-465881381",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]




 












Achtung Adressänderung:
Bitte richten Sie Ihre Post an die Unternehmenszentrale zukünftig an: adesso AG
| Adessoplatz 1 | 44269 Dortmund


-------------------------------------------------------     >>> business. people. technology. <<<-------------------------------------------------------adesso AG mit Sitz in DortmundVorstand: Michael Kenfenheuer (Vors.), Christoph Junge, Dirk Pothen, Andreas PrenneisVorsitzender des Aufsichtsrates: Prof. Dr. Volker GruhnAmtsgericht Dortmund HRB 20663
