### ISSUE TITLE
Refactoring of the 'ressources' package in the frontend branch

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#53]
I'm currently working with the new frontend, so for that I want to remove the old or unnecessary stuff.
So here are the thing I want to remove. If you have anything **to add** oder that you think we should **keep**, please raise your voice.

So I would suggest removing the following:
- The old header and everything related (CSS)
- The impressum
- The old home page (we dont need it anymore) and everything related (JS and CSS)
- 'simple_user_searchbar.html' (I did this and it isn't usable anymore)
- Everything related to the matches except add as base for the 'match result form'
- Everything related to login and registration as we use KeyCloak

I also would like discussing the following pages as I dont know which is really needed:
- Football Icon (we use Fontawesome, so do we really need them, we don't use them anywhere)
- There is a '_cookieWarning.js' and a 'cookieWarn.js' and there are in use BOTH. They only differ by one line of code, doesn't look like thats intended, we should only keep one)
- Error pages 400 and 404 (they seem usable to me, but I'm not shure if you think so too)
- Index.html (is outdated, we can make a new one if it is required)

Seeking for your Feedback!

**Comment by ccaylak** [comment]
I think we can basically remove the entire `template` Folder as we've used Bootstrap. We neither need `_cookieWarning.js` or `cookieWarning.js` as Tom mentioned: 
> So ein Feature wie "Cookie Consent" ist für eine interne Anwendung überflüssig. Konzentriert euch lieber auf Features, die die Anwendung voran bringen. Fragt euch bei allem, was ihr umsetzt "brauchen wir das für die erste Version wirklich?". Stichwort "Minimal Viable Product" (das könnt ihr mal googeln (Lächeln)).

**Comment by JanSchneider1** [comment]
@ccaylak Thinking of the principle of 'Minimal Viable Product' and its use of an intern application we should get rid of the cookies, index and impressum (yes this is basically the entire template folder)

**Comment by czarnecki** [comment]
I believe we can remove everything in the templates folder but match/* and we can remove the static folder completely as it's mostly outdated by now.

**Comment by Flo4l** [comment]
affirmative
