### ISSUE TITLE
Choose a ranking algorithm

### ISSUE THREAD

**Issue by czarnecki** [adessoAG/adessoKicker#6]
For the ranking system that has to be implemented we need to decide on an algorithm.

Some possibilities from the top of my head are:
- Glicko2
- Elo

**Comment by JanSchneider1** [comment]
I did a little bit of research about the two. We should choose Glicko2 as it is an enhanched version of Elo. Some thing about Glicko2 that could interest us, could be the "rating volatility" which describes how consistent a player plays. That would be cool to find "abusive behaviour" if someone tries to "boost" themselves

**Comment by czarnecki** [comment]
Glicko2 or rather Glicko in general isn't really intended for our use case. We should instead use ELO or a similiar algorithm.

**Comment by czarnecki** [comment]
Decided on ELO, will close this issue now.
