### ISSUE TITLE
Create new frontend based on mockups

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#65]
Pages we need to create:

- Header
- Ranking
- Profile
- Matchresult

The goal of this issue is to create pages seperate to the backend. In the next sprint we would be able to plug in all functions from the backend.

**Comment by JanSchneider1** [comment]
Created the ranking page, here is the current preview on different devices.
Quite responsive, even if the pager buttons go down on really small devices.
But I think thats the best I can do right now.
![bildschirmfoto vom 2019-02-21 um 10 51 03](https://user-images.githubusercontent.com/43335130/53162400-3b89d500-35cc-11e9-9eb8-775261714df8.png)
![bildschirmfoto vom 2019-02-21 um 10 49 35](https://user-images.githubusercontent.com/43335130/53162428-46446a00-35cc-11e9-9326-c74ba28afaa8.png)
![bildschirmfoto vom 2019-02-21 um 11 35 13](https://user-images.githubusercontent.com/43335130/53162659-c8349300-35cc-11e9-9c7a-d1c7ade6f10f.png)

**Comment by czarnecki** [comment]
Personally I like the general design. I am just confused by the weird blue arrows and a colleague I showed this to was confused by "Siegesquote" being 1.5 as he expected a percentage and the 1.5 would suggest 150%. But he too liked the general design.

**Comment by JanSchneider1** [comment]
@czarnecki the blue arrows are page scrollers, so the table only load 10 users and with the arrows you can load the next 10 or the 10 before
For the 'Siegesquote' it looks a bit confusing right now, maybe "Siege/Niederlage" would fit better as its like K/D in Videogames. Meaning if you "Siegesquote" is 1.5 you win 1.5 games for every loss. But we will figure this out when we have the backend plugged in

**Comment by czarnecki** [comment]
Maybe putting the arrow horizontally under the table might make this a bit more obvious and might looks better on mobile/small devices.
So this: < >

**Comment by JanSchneider1** [comment]
its hard to place the arrows besides the table even with bootstrap (i tried). Also < > seem a bit counter intuitiv as you don't go left to right in a list more like up and down.

**Comment by czarnecki** [comment]
I meant below not besides the table.
And I asked again and a colleague thought that having the scroll buttons at the top and the bottom might be nice. (Imagine being on mobile, list goes to 7 have to scroll down to see the rest want to continue and have to go back up)
He also said that having arrows up/down or right/left is based on taste but up down might look weird at the bottom.

**Comment by JanSchneider1** [comment]
Oh yeah that sound like a good idea. Im sorry that I missunderstood you




Outlook für Android herunterladen





On Thu, Feb 21, 2019 at 12:04 PM +0100, "Florian Czarnecki"
<notifications@github.com> wrote:



I meant below not besides the table.
And I asked again and a colleague thought that having the scroll buttons at the top and the bottom might be nice. (Imagine being on mobile, list goes to 7 have to scroll down to see the rest want to continue and have to go back up)
He also said that having arrows up/down or right/left is based on taste but up down might look weird at the bottom.
—
You are receiving this because you were assigned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adessoAG/adessoKicker","title":"adessoAG/adessoKicker","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/adessoAG/adessoKicker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@czarnecki in #65: I meant below not besides the table.\r\nAnd I asked again and a colleague thought that having the scroll buttons at the top and the bottom might be nice. (Imagine being on mobile, list goes to 7 have to scroll down to see the rest want to continue and have to go back up)\r\nHe also said that having arrows up/down or right/left is based on taste but up down might look weird at the bottom."}],"action":{"name":"View Issue","url":"https://github.com/adessoAG/adessoKicker/issues/65#issuecomment-465958199"}}}[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/adessoAG/adessoKicker/issues/65#issuecomment-465958199",
"url": "https://github.com/adessoAG/adessoKicker/issues/65#issuecomment-465958199",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]




 












Achtung Adressänderung:
Bitte richten Sie Ihre Post an die Unternehmenszentrale zukünftig an: adesso AG
| Adessoplatz 1 | 44269 Dortmund


-------------------------------------------------------     >>> business. people. technology. <<<-------------------------------------------------------adesso AG mit Sitz in DortmundVorstand: Michael Kenfenheuer (Vors.), Christoph Junge, Dirk Pothen, Andreas PrenneisVorsitzender des Aufsichtsrates: Prof. Dr. Volker GruhnAmtsgericht Dortmund HRB 20663

**Comment by JanSchneider1** [comment]
![screenshot_2019-02-21 adesso kicker](https://user-images.githubusercontent.com/43335130/53166737-7133bb80-35d6-11e9-81ba-60bf3f8dff51.png)
![screenshot_2019-02-21 adesso kicker 1](https://user-images.githubusercontent.com/43335130/53166738-7133bb80-35d6-11e9-986c-0899eed1d9fb.png)

I think I fixed it now, looks really cool in my opinion. The arrows change depending on the screen size.

**Comment by ccaylak** [comment]
I love the Design, I appreciate your work!

**Comment by JanSchneider1** [comment]
![screenshot_2019-02-25 adesso kicker 2](https://user-images.githubusercontent.com/43335130/53322673-5f0a9380-38dc-11e9-82e8-b1b75a7571a8.png)
![screenshot_2019-02-25 adesso kicker 3](https://user-images.githubusercontent.com/43335130/53322679-60d45700-38dc-11e9-8d07-87eedeba812e.png)
![screenshot_2019-02-25 adesso kicker](https://user-images.githubusercontent.com/43335130/53322683-65990b00-38dc-11e9-9016-88cab475ec85.png)
![screenshot_2019-02-25 adesso kicker 1](https://user-images.githubusercontent.com/43335130/53322690-6893fb80-38dc-11e9-9732-4b05b52677c0.png)

Added the profile and matchresult pages. they are kind of basic right now. I will wait for further feedback and polish the sites further more, so we can get some nice and clean frontend design.

**Comment by ccaylak** [comment]
Looks fine!

**Comment by Flo4l** [comment]
Yes, looks very nice!
Wouldn't it be possible to load more matches automatically by scrolling down?

**Comment by czarnecki** [comment]
Closed by #74
