### ISSUE TITLE
Email notifications for match outcome verification

### ISSUE THREAD

**Issue by czarnecki** [adessoAG/adessoKicker#7]
To reduce the chance of abusing the ranking system we need to have players verify the outcome of matches. Besides the notifications on the site we have to send one by mail.

**Comment by ccaylak** [comment]
Added the basic funtionality for emails. I came up with some ideas, what do you think about it? @czarnecki 
First case you create a match to verify. Message should look like this. 
From: AdessoKicker
To: PlayerA1, PlayerA2
Subject: Match, MatchId from Date
Text: You've sent (Enemies) a verification-request for your recently played match. (Winner) has won.

Second case, you get the verification request to verify.
From: AdessoKicker
To: PlayerB1, PlayerB2
Subject: Match, MatchId from Date
Text: You've recently played a match against (Enemies). (Winner) has won. Klick here to verify or here to decline.
