### ISSUE TITLE
Create labels for issues

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#8]
We need some labels to seperate our tasks, please leave some suggestions below

**Comment by JanSchneider1** [comment]
I would would consider following labels:
Bug       -> For bugs
Feature -> An Idea someone wants to implements
Refactoring -> Bad code need to be clean code

**Comment by ccaylak** [comment]
> I would would consider following labels:
> Bug -> For bugs
> Feature -> An Idea someone wants to implement
> Refactoring -> Bad code need to be clean code

I would recommend removing the "Feature" label as we've mentioned it today. It will end up causing feature creep.
