### ISSUE TITLE
Improve UX and design choices

### ISSUE THREAD

**Issue by JanSchneider1** [adessoAG/adessoKicker#81]
First feedback on the new frontend showed different things to improve/change:

- Orange color seems distracting and unfitting (change to black)
- Less animation (more sutle animation if use of animation)
- Change 'hitbox' of custom radiobuttons

**Comment by Flo4l** [comment]
Maybe rather change range to adesso blue than black.
I'm fine with most of the animations because they make the page a bit more awesome.

**Comment by Flo4l** [comment]
We also could/should set a custom tab icon.

**Comment by JanSchneider1** [comment]
> 
> 
> We also could/should set a custom tab icon.

All adesso sites use the adesso tab logo as their tab logo we should do so too

**Comment by JanSchneider1** [comment]
![screenshot_2019-03-04 adesso kicker](https://user-images.githubusercontent.com/43335130/53730638-ce522b80-3e78-11e9-8083-0b83d40020d0.png)

Please check out the update at the frontend branch and please give me some feedback.
I added new custom radio buttons, because the standard radio buttons are not responsive.
I also added a tooltip at the top right corner
